=== HidekazuFutagami-Takeda/RDM/bin/rule/rule.dtd
<!--
ALL RIGHTS RESERVED,
COPYRIGHT (C) 2013, HITACHI SOLUTIONS, Ltd.
-->
<!-- version 2.7.0 -->
<!ENTITY % ruleType "label|text|vlist">

<!ELEMENT rule (file|(sheet)*)>
<!ATTLIST rule input CDATA #IMPLIED>
<!ATTLIST rule output CDATA #IMPLIED>
<!ATTLIST rule maxColumn CDATA #IMPLIED>
<!ATTLIST rule maxRow CDATA #IMPLIED>
<!ATTLIST rule cdata (true|false) "false">

<!ELEMENT file (sheet)*>
<!ATTLIST file toName CDATA #IMPLIED>

<!ELEMENT sheet (block|(%ruleType;))*>
<!ATTLIST sheet index CDATA #REQUIRED>
<!ATTLIST sheet exclude CDATA #IMPLIED>
<!ATTLIST sheet toName CDATA #IMPLIED>

<!ELEMENT block (%ruleType;)*>
<!ATTLIST block toName CDATA #REQUIRED>

<!ELEMENT label EMPTY>
<!ATTLIST label match CDATA #IMPLIED>
<!ATTLIST label column CDATA #IMPLIED>
<!ATTLIST label row CDATA #IMPLIED>
<!ATTLIST label toName CDATA #IMPLIED>
<!ATTLIST label direction (right|bottom) "right">
<!ATTLIST label delimitedBy CDATA "">
<!ATTLIST label isDouble (true|false) "false">
<!ATTLIST label trim (true|false) "false">
<!ATTLIST label required (true|false) "false">
<!ATTLIST label hankaku (true|false) "false">
<!ATTLIST label lineseparator (true|false) "false">
<!ATTLIST label delete CDATA #IMPLIED>
<!ATTLIST label mask CDATA #IMPLIED>

<!ELEMENT text (label|vlist)*>
<!ATTLIST text match CDATA #IMPLIED>
<!ATTLIST text column CDATA #IMPLIED>
<!ATTLIST text row CDATA #IMPLIED>
<!ATTLIST text toName CDATA #IMPLIED>
<!ATTLIST text direction (right|bottom) "bottom">
<!ATTLIST text blankRow CDATA #IMPLIED>
<!ATTLIST text blankLine CDATA #IMPLIED>
<!ATTLIST text trim (true|false) "false">
<!ATTLIST text required (true|false) "false">
<!ATTLIST text hankaku (true|false) "false">
<!ATTLIST text lineseparator (true|false) "false">
<!ATTLIST text delete CDATA #IMPLIED>
<!ATTLIST text mask CDATA #IMPLIED>

<!ELEMENT vlist (property)*>
<!ATTLIST vlist match CDATA #IMPLIED>
<!ATTLIST vlist column CDATA #IMPLIED>
<!ATTLIST vlist row CDATA #IMPLIED>
<!ATTLIST vlist toName CDATA #IMPLIED>
<!ATTLIST vlist direction (right|bottom) "bottom">

<!ELEMENT property (subProperty)*>
<!ATTLIST property match CDATA #REQUIRED>
<!ATTLIST property toName CDATA #IMPLIED>
<!ATTLIST property delimitedBy CDATA "">
<!ATTLIST property isDouble (true|false) "false">
<!ATTLIST property trim (true|false) "false">
<!ATTLIST property required (true|false) "false">
<!ATTLIST property hankaku (true|false) "false">
<!ATTLIST property lineseparator (true|false) "false">
<!ATTLIST property delete CDATA #IMPLIED>
<!ATTLIST property mask CDATA #IMPLIED>

<!ELEMENT subProperty (subProperty)*>
<!ATTLIST subProperty match CDATA #REQUIRED>
<!ATTLIST subProperty toName CDATA #IMPLIED>
<!ATTLIST subProperty delimitedBy CDATA "">
<!ATTLIST subProperty isDouble (true|false) "false">
<!ATTLIST subProperty trim (true|false) "false">
<!ATTLIST subProperty required (true|false) "false">
<!ATTLIST subProperty hankaku (true|false) "false">
<!ATTLIST subProperty lineseparator (true|false) "false">
<!ATTLIST subProperty delete CDATA #IMPLIED>
<!ATTLIST subProperty mask CDATA #IMPLIED>

=== HidekazuFutagami-Takeda/RDM/bin/rule/sql-rule.xml
<?xml version="1.0" encoding="Windows-31J"?>
<!DOCTYPE rule SYSTEM "rule.dtd">
<rule input="SQL定義書" output="sql.xml">
    <sheet index="*" toName="SQL定義" exclude="表紙,変更履歴,template_SQL,master">
        <label match="システム名" />
        <label match="サブシステムID" />
        <label match="テーブル物理名" />
        <label match="版" direction="bottom" />
        <label match="更新者" direction="bottom" />
        <label match="更新日" direction="bottom" />
        <label match="SQL種別" />
        <label match="SQL ID" toName="SQLID" />
        <label match="説明" />
        <label match="SQL" />
        <label match="除外テーブルカラム名" direction="bottom" />
        <label match="テーブル名一覧" direction="bottom" />
        <vlist match="パラメータ定義">
            <property match="変数名" required="true" />
            <property match="No." />
            <property match="パラメータ名" />
            <property match="変数型" />
            <property match="備考" />
            <property match="テスト*" toName="test" />
        </vlist>
        <vlist match="エンティティ定義">
            <property match="変数名" required="true" />
            <property match="No." />
            <property match="項目名" />
            <property match="列物理名" />
            <property match="変数型" />
            <property match="SQL型" />
            <property match="ソート順" />
            <property match="除外" />
            <property match="備考" />
        </vlist>
    </sheet>
    <sheet index="master">
        <text match="変数型" />
        <text match="SQL型" />
    </sheet>
</rule>

=== HidekazuFutagami-Takeda/RDM/bin/rule/table-rule.xml
<?xml version="1.0" encoding="Windows-31J"?>
<!DOCTYPE rule SYSTEM "rule.dtd">
<rule input="テーブル定義書" output="table.xml">
    <sheet index="*" toName="テーブル定義" exclude="表紙,変更履歴">
        <label match="システム名" />
        <label match="サブシステムID" />
        <label match="テーブル物理名" />
        <label match="テーブル論理名" />
        <vlist match="列定義">
            <property match="No." />
            <property match="列物理名" />
            <property match="列論理名" />
            <property match="SQL型" />
            <property match="桁数" />
            <property match="PK" />
            <property match="NOT NULL" toName="NOTNULL" />
            <property match="ソート" />
            <property match="説明" />
            <property match="備考" />
            <property match="変数名" />
            <property match="変数型" />
        </vlist>
    </sheet>
</rule>

=== HidekazuFutagami-Takeda/RDM/bin/rule/validation-rule-rule.xml
<?xml version="1.0" encoding="Windows-31J"?>
<!DOCTYPE rule SYSTEM "rule.dtd">
<rule input="検証ルール一覧" output="validation-rule.xml">
    <sheet index="*" toName="ルール">
        <vlist match="検証ルール">
            <property match="検証ルール日本語名" />
            <property match="No" />
            <property match="検証ルール名" />
            <property match="属性定義" >
                <subProperty match="属性1">
                    <subProperty match="属性名" />
                    <subProperty match="属性型" />
                  <subProperty match="属性値" />
                  </subProperty>
                <subProperty match="属性2">
                    <subProperty match="属性名" />
                    <subProperty match="属性型" />
                    <subProperty match="属性値" />
                </subProperty>
                <subProperty match="属性3">
                    <subProperty match="属性名" />
                    <subProperty match="属性型" />
                    <subProperty match="属性値" />
                </subProperty>
                <subProperty match="属性4">
                    <subProperty match="属性名" />
                    <subProperty match="属性型" />
                    <subProperty match="属性値" />
                </subProperty>
            </property>
            <property match="メッセージID" />
        </vlist>
    </sheet>
</rule>

=== HidekazuFutagami-Takeda/RDM/bin/rule/common-rule.xml
<?xml version="1.0" encoding="Windows-31J"?>
<!DOCTYPE rule SYSTEM "rule.dtd">
<rule input="共通" output="common.xml">
    <sheet index="*共通設定*" toName="共通設定">
        <label match="設計情報フォルダ" />
        <label match="ソースフォルダ" />
        <label match="JSPフォルダ" />
        <label match="WEB-INFフォルダ" />
        <label match="ルートパッケージ" />
        <label match="DTOパッケージ" />
        <label match="Actionパッケージ" />
        <label match="Serviceパッケージ" />
        <label match="Entityパッケージ" />
        <label match="共通パッケージ" />
        <label match="Exceptionパッケージ" />
        <!-- フレームワーク -->
        <label match="P層フレームワーク" />
        <label match="F層フレームワーク" />
        <label match="D層フレームワーク" />
        <!-- DB設定 -->
        <label match="データソースタイプ" />
        <label match="データソース名" />
        <label match="ドライバクラス" />
        <label match="接続URL" />
        <label match="ユーザ名" />
        <label match="パスワード" />
        <!-- 生成 -->
        <label match="Lombok使用" />
        <label match="Javaエンコーディング" />
        <label match="XMLエンコーディング" />
        <label match="メッセージリソースエンコーディング" />
        <label match="リクエストエンコーディング" />
        <!-- 共通部品設定 -->
        <label match="排他キー名" />
        <label match="ログインチェック除外パス" />
        <label match="直打ち許可パス" />
        <label match="直打ち禁止パス" />
        <label match="画面利用権限チェック" />
        <label match="利用時間帯チェック" />
    </sheet>
</rule>

=== HidekazuFutagami-Takeda/RDM/bin/rule/screenvalidation-rule.xml
<?xml version="1.0" encoding="Windows-31J"?>
<!DOCTYPE rule SYSTEM "rule.dtd">
<rule input="画面項目定義書" output="screenvalidation.xml" maxColumn="200">
    <sheet index="*入力チェック定義*" toName="入力チェック定義">
        <!-- 全体共通設定 -->
        <label match="システム名" />
        <label match="サブシステム名" />
        <label match="画面ID" />
        <label match="画面名" />
        <label match="更新者" direction="bottom" />
        <label match="更新日" direction="bottom" />
        <vlist match="入力チェック">
            <property match="イベントID" />
            <property match="No." />
            <property match="項目ID" />
            <property match="繰返変数名" />
            <property match="入力形式" />
            <property match="属性" >
                <subProperty match="属性値1" />
                <subProperty match="属性値2" />
                <subProperty match="属性値3" />
                <subProperty match="属性値4" />
            </property>
            <property match="メッセージID" />
        </vlist>
    </sheet>
</rule>

=== HidekazuFutagami-Takeda/RDM/bin/rule/screenevent-rule.xml
<?xml version="1.0" encoding="Windows-31J"?>
<!DOCTYPE rule SYSTEM "rule.dtd">
<rule input="画面項目定義書" output="screenevent.xml" maxColumn="200" maxRow="500">
    <sheet index="*イベント定義*" toName="イベント定義">
        <label match="システム名" />
        <label match="サブシステムID" />
        <label match="画面ID" />
        <label match="画面名" />
        <label match="更新者" direction="bottom" />
        <label match="更新日" direction="bottom" />
        <vlist match="イベント">
            <property match="イベントID" required="true" />
            <property match="No." />
            <property match="遷移先画面ID" />
            <property match="遷移タイプ" />
            <property match="検証" />
            <property match="トークンチェック" />
            <property match="権限" />
            <property match="備考"/>
        </vlist>
    </sheet>
</rule>

=== HidekazuFutagami-Takeda/RDM/bin/rule/screenmessage-rule.xml
<?xml version="1.0" encoding="Windows-31J"?>
<!DOCTYPE rule SYSTEM "rule.dtd">
<rule input="画面メッセージ一覧" output="screenmessage.xml">
    <sheet index="1">
        <label match="システム名" />
        <vlist match="詳細情報">
            <property match="項番" />
            <property match="メッセージID" />
            <property match="画面メッセージ" />
            <property match="可変項目1" toName="可変項目" />
            <property match="可変項目2" toName="可変項目" />
            <property match="可変項目3" toName="可変項目" />
            <property match="可変項目4" toName="可変項目" />
            <property match="可変項目5" toName="可変項目" />
            <property match="備考" />
        </vlist>
    </sheet>
</rule>

=== HidekazuFutagami-Takeda/RDM/bin/rule/screenitem-rule.xml
<?xml version="1.0" encoding="Windows-31J"?>
<!DOCTYPE rule SYSTEM "rule.dtd">
<rule input="画面項目定義書" output="screenitem.xml" maxColumn="200">
    <sheet index="*画面項目定義*" toName="画面項目定義">
        <label match="システム名" />
        <label match="サブシステムID" />
        <label match="画面ID" />
        <label match="画面名" />
        <label match="更新者" direction="bottom" />
        <label match="更新日" direction="bottom" />
        <vlist match="画面項目">
            <property match="項目名" required="true" />
            <property match="No." />
            <property match="入出力" />
            <property match="種別" />
            <property match="備考"/>
            <!-- P層設計 -->
            <property match="項目ID"/>
            <property match="変数型" />
            <property match="繰返変数名" />
            <property match="初期値" />
        </vlist>
    </sheet>
</rule>
